### ISSUE TITLE
Feat: Add Favicon 

### ISSUE THREAD

**Issue by satyamksharma** [SarthakSKumar/QuickSend#10]
**Define You**

- [x] Hacktoberfest Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
Updating the default nextJS favicon to the web app favicon

**Describe the solution you'd like...**
Adding a new favicon to the web app

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by SarthakSKumar** [comment]
Hi @satyamksharma 
Issue assigned!
