### ISSUE TITLE
Feat: Improvise UI 2.0

### ISSUE THREAD

**Issue by satyamksharma** [SarthakSKumar/QuickSend#13]
**Define You**

- [x] Hacktoberfest Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
No this feature is just an enhancement

**Describe the solution you'd like...**
Added some animation and cool backgrounds

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by satyamksharma** [comment]
hi there, can u assign me this issue

**Comment by SarthakSKumar** [comment]
Issue assigned @satyamksharma

**Comment by its-abhishek** [comment]
hey @SarthakSKumar , can i work on this issue

**Comment by SarthakSKumar** [comment]
@its-abhishek A PR resolving this issue will soon be created by @satyamksharma, and is working on this issue currently.

**Comment by SarthakSKumar** [comment]
@its-abhishek Do you want to work on this issue?

**Comment by its-abhishek** [comment]
@SarthakSKumar yes

**Comment by SarthakSKumar** [comment]
Assigned @its-abhishek

**Comment by SarthakSKumar** [comment]
Any updates? @its-abhishek

**Comment by SarthakSKumar** [comment]
Issue is now being closed!
