### ISSUE TITLE
Bug: Text color of country not visible on selecting

### ISSUE THREAD

**Issue by yube01** [SarthakSKumar/QuickSend#17]
**Define You**

- [x] Hacktoberfest Participant  
- [x] Contributor

**Describe the Bug**
While selecting country name all text color is white so it looks invisible

**Steps to Reproduce**

1. Changing text color
2. 
3. 
4. 

**Expected Behavior**

**Actual Behavior**

**Screenshots/Block Diagram/Emulator Prototype Diagram**

**Additional Details**

**Comment by SarthakSKumar** [comment]
Hi @yube01 
There is an issue open already, which addresses this problem. You can work on the issue if the current assignee is not able to do it.
#13

**Comment by its-abhishek** [comment]
@SarthakSKumar can i work on this issue

**Comment by SarthakSKumar** [comment]
Issue is now being closed!
