### ISSUE TITLE
Feat: Improvise UI

### ISSUE THREAD

**Issue by SarthakSKumar** [SarthakSKumar/QuickSend#4]
**Define You**

- [ ] Hacktoberfest Participant 
- [ ] Contributor
- [x] Maintainer

**Describe the solution you'd like...**

Create an appealing responsive UI for this application

**Approach to be followed (optional):**

Use Tailwind CSS. Define a theme in tailwind.config.js and maintain consistent design across the application

**Comment by BoshraJaber** [comment]
Hello @SarthakSKumar 
I would love to help 
Please assign me if help is still needed

**Comment by SarthakSKumar** [comment]
Sure. Issue Assigned!
@BoshraJaber

**Comment by SarthakSKumar** [comment]
Hi. Is there any progress? @BoshraJaber

**Comment by satyamksharma** [comment]
Hi @SarthakSKumar can I work in this issue

**Comment by SarthakSKumar** [comment]
Reassigned to @satyamksharma
