### ISSUE TITLE
Feat: Configure next/pwa to create a PWA Application

### ISSUE THREAD

**Issue by SarthakSKumar** [SarthakSKumar/QuickSend#5]
**Define You**

- [ ] Hacktoberfest Participant 
- [ ] Contributor
- [x] Maintainer

**Comment by its-abhishek** [comment]
Hi @SarthakSKumar ,
I love to contribute to this issue,
plss assign this issue

**Comment by SarthakSKumar** [comment]
Assigned @its-abhishek :)

**Comment by SarthakSKumar** [comment]
Any update @its-abhishek ?

**Comment by SarthakSKumar** [comment]
Issue Resolved @its-abhishek . Closing now.
Thank you :)
