### ISSUE TITLE
Bug: Phone number and select country text is not clearly visible

### ISSUE THREAD

**Issue by rizul11** [SarthakSKumar/QuickSend#6]
Description:

The phone number and select country text are not clearly visible on the page. This makes it difficult to enter my contact information.

Video :
https://github.com/SarthakSKumar/QuickSend/assets/88412712/1c493ee1-1178-4cae-8cba-14784346ea9c

Reproduction case:

- Go to the page where the phone number and select country text are located.
- Try to enter your contact information.
- The phone number and select country text will be difficult to see.

Labels: bug

Additional information:

I am new to this and this is my first time creating issues and making open source contributions.

**Comment by SarthakSKumar** [comment]
Issue assigned @rizul11 
Thanks for raising this issue. Please make sure you don't create a Pull Request until you are assigned an issue to work on :)
