### ISSUE TITLE
Feat: Add light and dark mode support

### ISSUE THREAD

**Issue by rizul11** [SarthakSKumar/QuickSend#8]
Description :

I would like to add light and dark mode support to the project. This would allow users to choose the display mode that they prefer, which would make the project more accessible and user-friendly. 

I am happy to implement light and dark mode support in the project.  Please let me know if you have any questions or feedback.

**Comment by SarthakSKumar** [comment]
Please work on one issue at a time. This issue will be assigned on closing #6 @rizul11

**Comment by SarthakSKumar** [comment]
Assigned @rizul11
