### ISSUE TITLE
Bug: Error comes whenever we type something else then a number

### ISSUE THREAD

**Issue by rizul11** [SarthakSKumar/QuickSend#9]
Description: 
I encountered an unhandled runtime error whenever i type something else then a number
The error message is as follows : 
Unhandled Runtime Error: TypeError: A text for parsing must be a string.

Steps to Reproduce:
i) Click on phone number input box .
ii) Type something other than a number like any letter or even start with a backspace.
iii) You will face error moment you type. 

Error Video:

https://github.com/SarthakSKumar/QuickSend/assets/88412712/8a6a4d76-2382-46ce-a119-eaad1f369e59

Possible Solutions: 
I was not able to solve error on my own but i believe its due to some conditions in 
react-phone-number-input , i  might be wrong . If you have any suggestions or ideas for a possible solution, feel free to share them here.

**Comment by SarthakSKumar** [comment]
Please work on one issue at a time. This issue will be assigned on closing #6 @rizul11

**Comment by paardarshee** [comment]
Hey @SarthakSKumar 
I faced the same issue
@rizul11 created this, But as he mentioned that, he was not solve that error
Assign It to me, I Can figure out the error

**Comment by SarthakSKumar** [comment]
Hi @TheCodeVenturer 
You can work on the issue.

**Comment by paardarshee** [comment]
@SarthakSKumar, why page.js has 100+ lines of code commented?
Do i remove it?

**Comment by rizul11** [comment]
> @SarthakSKumar, why page.js has 100+ lines of code commented? Do i remove it?

Sorry my bad coding habits
